customhost = "employee.cgimzc2nhmtc.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "employee"
custombucket = "chanmingfoon-employee"
customregion = "us-east-1"
